/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazUsuario;

import Logistica.WebCamControl;
import javax.swing.ImageIcon;

/**
 *
 * @author Oscar
 */
public class dlgCapturaFotografia extends javax.swing.JDialog {
    String nombre;

    /**
     * Creates new form dlgCapturaFotografia
     */
    public dlgCapturaFotografia(java.awt.Frame parent, boolean modal, String nombre) {
        super(parent, modal);
        initComponents();
        btnFoto.setEnabled(false);
        this.nombre = nombre;
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnViendo = new javax.swing.JButton();
        btnFoto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Mazorca.png"))); // NOI18N

        btnViendo.setText("Vamos viendo pues pariente");
        btnViendo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViendoActionPerformed(evt);
            }
        });

        btnFoto.setText("Tome la foto pariente");
        btnFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel1)
                .addContainerGap(109, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(btnViendo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFoto)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViendo)
                    .addComponent(btnFoto))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnViendoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViendoActionPerformed
        // TODO add your handling code here:
     //   WebCamControl camaraVideo = new WebCamControl();
        camaraVideo.letMeSee();
        btnFoto.setEnabled(true);
        btnViendo.setEnabled(false);
        
        
    }//GEN-LAST:event_btnViendoActionPerformed

    private void btnFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFotoActionPerformed
        // TODO add your handling code here:
        WebCamControl ins = new WebCamControl();
        try {
            if(ins.tomaFoto()) { 
                ImageIcon foto = new ImageIcon("test.png");
                dispose();
                camaraVideo.cierrome();
                dlgHowDoILook dlg = new dlgHowDoILook(null, true, nombre);
                dlg.setVisible(true);
                
           
            }
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_btnFotoActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFoto;
    private javax.swing.JButton btnViendo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    WebCamControl camaraVideo = new WebCamControl();
}
