/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazUsuario;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import musica.CancionCuatro;
import musica.CancionDos;
import musica.CancionTres;
import musica.CancionUno;

/**
 *
 * @author Oscar
 */
public class dlgEscogeCancion extends javax.swing.JDialog {

    CancionUno insCancionUno = new CancionUno();
    CancionDos insCancionDos = new CancionDos();
    CancionTres insCancionTres = new CancionTres();
    CancionCuatro insCancionCuatro = new CancionCuatro();
    String nombre;
    
    int cancionSeleccionada;
    /**
     * Creates new form dlgEscogeCancion
     */
    public dlgEscogeCancion(java.awt.Frame parent, boolean modal, String nombre) {
        super(parent, modal);
        initComponents();
        lblCancionUno.setText("");
        lblCancionUno.setIcon(cancionUnoSinFocus);
        btnJugar.setEnabled(false);
        this.nombre = nombre;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblCancionUno = new javax.swing.JLabel();
        lblCancionDos = new javax.swing.JLabel();
        lblCancionTres = new javax.swing.JLabel();
        lblCancionCuatro = new javax.swing.JLabel();
        btnJugar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/escogerMusica.png"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblCancionUno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/tololocheChicoteadoSinFocus.png"))); // NOI18N
        lblCancionUno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCancionUnoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCancionUnoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCancionUnoMouseExited(evt);
            }
        });

        lblCancionDos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancion2SinFocus.png"))); // NOI18N
        lblCancionDos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCancionDosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCancionDosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCancionDosMouseExited(evt);
            }
        });

        lblCancionTres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancion3SinFocus.png"))); // NOI18N
        lblCancionTres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCancionTresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCancionTresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCancionTresMouseExited(evt);
            }
        });

        lblCancionCuatro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancion4SinFocus.png"))); // NOI18N
        lblCancionCuatro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCancionCuatroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCancionCuatroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCancionCuatroMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCancionUno)
                    .addComponent(lblCancionDos)
                    .addComponent(lblCancionTres)
                    .addComponent(lblCancionCuatro))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCancionUno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCancionDos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCancionTres)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCancionCuatro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnJugar.setText("Vamos jugando pariente");
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnJugar)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(btnJugar)
                .addGap(22, 22, 22))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCancionUnoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancionUnoMouseEntered
        // TODO add your handling code here:
        lblCancionUno.setIcon(cancionUnoConFocus);
        insCancionUno.queSuenaPariente();
        
      
    }//GEN-LAST:event_lblCancionUnoMouseEntered

    private void lblCancionUnoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancionUnoMouseExited
        // TODO add your handling code here:
        lblCancionUno.setIcon(cancionUnoSinFocus);
        insCancionUno.silencioPariente();
    }//GEN-LAST:event_lblCancionUnoMouseExited

    private void lblCancionDosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancionDosMouseEntered
        // TODO add your handling code here:
        lblCancionDos.setIcon(cancionDosConFocus);
        insCancionDos.queSuenaPariente();
    }//GEN-LAST:event_lblCancionDosMouseEntered

    private void lblCancionDosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancionDosMouseExited
        // TODO add your handling code here:
        lblCancionDos.setIcon(cancionDosSinFocus);
        insCancionDos.silencioPariente();
    }//GEN-LAST:event_lblCancionDosMouseExited

    private void lblCancionTresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancionTresMouseEntered
        // TODO add your handling code here:
        lblCancionTres.setIcon(cancionTresConFocus);
        insCancionTres.queSuenaPariente();
    }//GEN-LAST:event_lblCancionTresMouseEntered

    private void lblCancionTresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancionTresMouseExited
        // TODO add your handling code here:
        lblCancionTres.setIcon(cancionTresSinFocus);
        insCancionTres.silencioPariente();
    }//GEN-LAST:event_lblCancionTresMouseExited

    private void lblCancionCuatroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancionCuatroMouseEntered
        // TODO add your handling code here:
        lblCancionCuatro.setIcon(cancionCuatroConFocus);
        insCancionCuatro.queSuenaPariente();
    }//GEN-LAST:event_lblCancionCuatroMouseEntered

    private void lblCancionCuatroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancionCuatroMouseExited
        // TODO add your handling code here:
        lblCancionCuatro.setIcon(cancionCuatroSinFocus);
        insCancionCuatro.silencioPariente();
    }//GEN-LAST:event_lblCancionCuatroMouseExited

    private void lblCancionUnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancionUnoMouseClicked
        // TODO add your handling code here:
        cancionSeleccionada = 1;
        btnJugar.setEnabled(true);
    }//GEN-LAST:event_lblCancionUnoMouseClicked

    private void lblCancionDosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancionDosMouseClicked
        // TODO add your handling code here:
        cancionSeleccionada = 2;
        btnJugar.setEnabled(true);
    }//GEN-LAST:event_lblCancionDosMouseClicked

    private void lblCancionTresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancionTresMouseClicked
        // TODO add your handling code here:
        cancionSeleccionada = 3;
        btnJugar.setEnabled(true);
    }//GEN-LAST:event_lblCancionTresMouseClicked

    private void lblCancionCuatroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancionCuatroMouseClicked
        // TODO add your handling code here:
        cancionSeleccionada = 4;
        btnJugar.setEnabled(true);
    }//GEN-LAST:event_lblCancionCuatroMouseClicked

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
        // TODO add your handling code here:
        
        JOptionPane.showMessageDialog(rootPane, "Cancion escogida: " + cancionSeleccionada);
        dispose();
        
        JOptionPane.showMessageDialog(rootPane, "Teclas: \n A, S, K, L.");
       
        DlgJuegoHilo instancia = new DlgJuegoHilo(null, false, nombre, cancionSeleccionada);
        instancia.setVisible(true);
        
        
    }//GEN-LAST:event_btnJugarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJugar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCancionCuatro;
    private javax.swing.JLabel lblCancionDos;
    private javax.swing.JLabel lblCancionTres;
    private javax.swing.JLabel lblCancionUno;
    // End of variables declaration//GEN-END:variables
    ImageIcon cancionUnoSinFocus = new ImageIcon("src\\Iconos\\tololocheChicoteadoSinFocus.png");
    ImageIcon cancionUnoConFocus = new ImageIcon("src\\Iconos\\tololocheChicoteadoConFocus.png");

     ImageIcon cancionDosSinFocus = new ImageIcon("src\\Iconos\\cancion2SinFocus.png");
     ImageIcon cancionDosConFocus = new ImageIcon("src\\Iconos\\cancion2ConFocus.png");
     
     ImageIcon cancionTresSinFocus = new ImageIcon("src\\Iconos\\cancion3SinFocus.png");
     ImageIcon cancionTresConFocus = new ImageIcon("src\\Iconos\\cancion3ConFocus.png");
     
     ImageIcon cancionCuatroSinFocus = new ImageIcon("src\\Iconos\\cancion4SinFocus.png");
     ImageIcon cancionCuatroConFocus = new ImageIcon("src\\Iconos\\cancion4ConFocus.png");
     
}
