/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazUsuario;

import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Oscar
 */
public class frmTestBeer extends javax.swing.JFrame {

    /**
     * Creates new form frmTestBeer
     */
    public frmTestBeer() {
        initComponents();
    }

    public void reduceCerveza() {
        switch (nivelCerveza) {
            case 100:
                nivelCerveza = 80;
                lblCerveza.setIcon(nivelCerveza80);
                break;
            case 80:
                nivelCerveza = 60;
                lblCerveza.setIcon(nivelCerveza60);
                break;
            case 60:
                nivelCerveza = 40;
                lblCerveza.setIcon(nivelCerveza40);
                break;
            case 40:
                nivelCerveza = 20;
                lblCerveza.setIcon(nivelCerveza20);
                break;
            case 20:
                nivelCerveza = 0;
                lblCerveza.setIcon(nivelCerveza0);
                break;
            case 0:
               
                break;

        }
    }

    public void aumentaCerveza() {

        switch (nivelCerveza) {
            case 100:
                break;
            case 0:
                nivelCerveza = 20;
                lblCerveza.setIcon(nivelCerveza20);
                break;
            case 20:
                nivelCerveza = 40;
                lblCerveza.setIcon(nivelCerveza40);
                break;
            case 40:
                nivelCerveza = 60;
                lblCerveza.setIcon(nivelCerveza60);
                break;
            case 60:
                nivelCerveza = 80;
                lblCerveza.setIcon(nivelCerveza80);
                break;
            case 80:
                nivelCerveza = 100;
                lblCerveza.setIcon(nivelCerveza100);
                break;

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCerveza = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCerveza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cerveza100.png"))); // NOI18N

        jButton1.setText("Error");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Acierto");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(lblCerveza)
                .addContainerGap(170, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(24, 24, 24)
                .addComponent(jButton2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(lblCerveza)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        aumentaCerveza();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        reduceCerveza();
    }//GEN-LAST:event_jButton1ActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel lblCerveza;
    // End of variables declaration//GEN-END:variables
    int nivelCerveza = 100;
    Icon nivelCerveza100 = new ImageIcon("src\\Iconos\\cerveza100.png");
    Icon nivelCerveza80 = new ImageIcon("src\\Iconos\\cerveza80.png");
    Icon nivelCerveza60 = new ImageIcon("src\\Iconos\\cerveza60.png");
    Icon nivelCerveza40 = new ImageIcon("src\\Iconos\\cerveza40.png");
    Icon nivelCerveza20 = new ImageIcon("src\\Iconos\\cerveza20.png");
    Icon nivelCerveza0 = new ImageIcon("src\\Iconos\\cerveza0.png");

}
